#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
#CC := /var/jenkins/workspace/ATC_BUILDROOT/src/src_buildroot/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-gcc
#CXX := /var/jenkins/workspace/ATC_BUILDROOT/src/src_buildroot/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-g++
LD := $(CXX)
#AR := /var/jenkins/workspace/ATC_BUILDROOT/src/src_buildroot/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-ar
#OBJCOPY := /var/jenkins/workspace/ATC_BUILDROOT/src/src_buildroot/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-objcopy

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1
INCLUDE_DIRS := SHARED/cpp-httplib-master
LIBRARY_DIRS := /var/jenkins/workspace/ATC_BUILDROOT/src/src_buildroot/buildroot/output/target/usr/lib/
LIBRARY_NAMES := c rt crypt m
ADDITIONAL_LINKER_INPUTS := -lpthread -ldl
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0 -std=c++17
CXXFLAGS := -ggdb -ffunction-sections -O0 -std=c++17
ASFLAGS := 
LDFLAGS := 
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := 
END_GROUP := 

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
