//
// Created by prodevmo on 29.04.21.
//

#ifndef CONTROLLER_VOICERECOGNITIONEXTENTION_H
#define CONTROLLER_VOICERECOGNITIONEXTENTION_H


class VoiceRecognitionExtention {

};


#endif //CONTROLLER_VOICERECOGNITIONEXTENTION_H
