#!/bin/sh

. /etc/init.d/functions

start() {
    /usr/ATC/atc_testpackage
    /usr/ATC/atc_ui
}

stop() {
  
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)

       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 