#!/bin/sh
# /etc/init.d/S77mountboot ATCProject Marcel Ochsendorf marcel.ochsendorf.com
#
# atc        Starts all ATC pacakges.
#



umask 077

start() {

	mount /dev/mmcblk0p1 /boot
	echo "OK"
}
stop() {

	umount /boot
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


