#!/bin/sh
# /etc/init.d/S95wifi ATCProject Marcel Ochsendorf marcelochsendorf.com
#
# atc        Starts all ATC pacakges.
#



umask 077

start() {
	printf "Starting WIFI"
	touch /usr/ATC/WIFI
	/usr/ATC/start_wifi.sh
	echo "OK"
}
stop() {
	printf "Stopping WIFI"
	rm -f /usr/ATC/WIFI
	#killall gensiot
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


