#!/bin/sh
# /etc/init.d/S99atcsrv ATCProject Marcel Ochsendorf marcelochsendorf.com
#
# atc        Starts ATC pacakges.
#



umask 077

start() {
	printf "Starting ATC DISCOVERY HELPER"
	touch /usr/ATC/ATC_LOCK_DCH
    /usr/ATC/start_atc_discoveryhelper.sh &
	echo "OK"
}
stop() {
	printf "Stopping ATC DISCOVERY HELPER"
	rm -f /usr/ATC/	touch /usr/ATC/ATC_LOCK_DCH
	killall atc_discovery_helper
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


