#!/bin/sh
# /etc/init.d/S99atc ATCProject Marcel Ochsendorf marcelochsendorf.com
#
# atc        Starts all ATC pacakges.
#



umask 077

start() {
	printf "MODPROBE i2c "
	modprobe i2c-dev
	printf "Starting ATC "
	touch /usr/ATC/ATC_LOCK
    	/usr/ATC/start_atc_gui.sh &
	/usr/ATC/start_atc_webui.sh &
	/usr/ATC/start_atc_controller.sh &
	echo "OK"
}
stop() {
	printf "Stopping ATC"
	rm -f /usr/ATC/ATC_LOCK
	killall atc_ui
	killall atc_controller
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


