#!/bin/sh
#
# atc        Starts atc pacakges.
#



umask 077

start() {

	modprobe i2c-dev
    /usr/ATC/atc_ui &
	/usr/ATC/atc_controller &
	printf "Starting atc: "
	touch /usr/ATC/ATC_LOCK
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall atc_ui
	killall atc_controller
	rm -f /usr/ATC/ATC_LOCK
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


