version: "3"
services:
  ThesisServer:
    container_name: thesisserver

    image: thesisserver:latest
    build:
      context: ./
    restart: always
    ports:
      - 3020:3020
    environment:
      - PRODUCTION=1
