version: "3"
services:
  AtomicChessExtentionVoiceRecognition:
    container_name: atcextvoicerecognition
    build:
      context: ../ATC_ExtentionVoiceRecognition/
    image: atcextvoicerecognition
    network_mode: "host"
    restart: always
    ports:
      - 8880:8880