#!/bin/sh
# /etc/init.d/S99atc ATCProject Marcel Ochsendorf marcel.ochsendorf.com
#
# atc        Starts the ATC ATC_DGT3000_EXT_LOCK pacakge.
#



umask 077

start() {
	printf "MODPROBE i2c "
	modprobe i2c-dev
	printf "Starting ATC_DGT3000_EXT_LOCK "
	touch /usr/ATC/ATC_DGT3000_EXT_LOCK
    /usr/ATC/start_atc_dgt3000.sh &
	echo "OK"
}
stop() {
	printf "Stopping ATC_DGT3000_EXT_LOCK"
	rm -f /usr/ATC/ATC_DGT3000_EXT_LOCK
	killall ATC_DGT3000_EXT
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


